/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Report Problem': '报告问题',
    'Abilities': '能力',
    'About': '关于',
    'Achievement': '成就',
    'Achievements': '成就',
    'Additional styling (advanced': '附加样式 (高级',
    'Close': '关闭',
    'Community': '社区',
    '- select unit --': '- 选择单位 --',
    '. Thanks!': '. 感谢!',
    'Velocity format': '速度格式',
    'import': '导入',
    'Import/export saved data': '导入/导出存档数据',
    'Login': '登录',
    'Logout': '登出',
    'minutes': '分钟',
    'hours': '小时',
    'More...': '更多...',
    'Number format': '数字格式',
    'Options': '选项',
    'options screen': '选项界面',
    'Please': '请',
    'Recovery email sent.': '恢复电子邮件已发送。',
    'Remember me': '记住我',
    'Sign up': '注册',
    'Skip time:': '时间跳跃:',
    'Statistics': '统计',
    'Theme': '主题',
    'This is a bug.': '这是一个错误。',
    'larva tab': '幼虫标签',
    'territory tab': '领土标签',
    'larvae': '幼虫',
    'Log in': '登录',
    'Password': '密码',
    'Patch Notes': '补丁说明',
    'patch notes screen': '补丁说明界面',
    'Placekitten': '小猫咪',
    'please try Chrome or Firefox': '请尝试用 Chrome 或 Firefox 浏览器',
    'save': '保存',
    'seconds': '秒',
    'Swarmwarps': '虫群扭曲',
    'Undo': '撤销',
    'Undo the last action': '撤销最后一个操作',
    'We\'ll only send you account recovery/lost password emails.': '我们只会向您发送帐户恢复/丢失密码的邮件。',
    'Where is Swarm Simulator\'s data saved?': '模拟虫群的数据保存在哪里?',
    'Wipe all saved data and start over': '擦除所有保存的数据，重新开始',
    'Swarm Simulator is now Kitten Klicker!': '模拟虫群现在是小猫点击！',
    'Swarm Simulator\'s been updated, and you\'re playing an old version.': '模拟虫群已更新了新版本，您正在玩的是旧的版本。',
    'Swarm Simulator\'s next big update, v1.2.0, will be ready soon.': '模拟虫群的下一个重大更新是 v1.2.0 ，将很快准备就绪。',
    'The error message was': '错误消息是',
    'There was a problem loading your saved game.': '在加载你保存的游戏时出现了问题。',
    'There was a problem saving your game.': '在保存你的游戏时出现了问题。',
    'This problem usually happens when your browser is': '这个问题通常发生在你的浏览器',
    'To remove them later, go to the options screen and click "Clear all extra styling/graphics".': '要删除它们，请到选项界面，点击“清除所有额外的样式/图形”。',
    'Try out the upcoming changes now!': '现在就尝试即将到来的变化吧!',
    'You lead a small brood of worker drones. Drones gather meat. Use this meat to build more drones and expand your brood.': '你领导着一群工蜂。工蜂收集肉。用这些肉来繁殖更多的工蜂，扩大你的巢穴。',
    'You can try it out today': '你今天可以试试',
    'You should play the latest Swarm Simulator!': '你应该玩最新版的模拟虫群!',
    'You will keep your saved progress once v1.2.0 is released.': '一旦v1.2.0发布，您将保持您当前的进度。',
    'achievements screen': '成就界面',
    'all-units tab': '全部单位标签',
    'energy tab': '能量标签',
    'meat tab': '肉标签',
    'report this bug': '报告这个错误',
    'Send Feedback': '发送反馈',
    'Set count:': '设置数量:',
    'Show all units': '显示全部单位',
    'Save this': '保存这个',
    'Show / hide this help menu': '显示/隐藏帮助菜单',
    'statistics screen': '统计界面',
    'Swarm Simulator': '模拟虫群',
    'Here\'s your saved game data.': '这是你保存的游戏数据。',
    'mutagen tab': '诱变标签',
    'export': '导出',
    'meat': '肉',
    'Swarm Simulator does not support the Safari browser. If you have trouble,': '模拟虫群不兼容 Safari浏览器。 如果你遇到麻烦，',
    'Please make sure': '请确保',
    'report it': '报告它',
    'drone': '工蜂',
    'contact the developer': '联系开发者',
    'Click here to keep the kitten pictures.': '单击这里保留小猫图片。',
    'Click here if you hate kittens, you monster.': '如果你讨厌小猫，点击这里，你这个怪物。',
    'larva': '幼虫',
    'Meat is delicious. All of your swarm\'s creatures eat meat.': '肉很好吃。你的虫群里所有的生物都吃肉。',
    'Never notify': '永远不要通知',
    'Next': '下一个',
    'Notify when buyable': '可购买时通知',
    'Select cocoons': '选择茧',
    'Select drones': '选择工蜂',
    'This ability costs': '这种能力花费',
    'upgrade costs': '升级花费',
    'Upgrades': '升级',
    'Select meat': '选择肉',
    'Select queens': '选择蜂后',
    'per second.': '每秒。',
    'once the bug is fixed, you can import this to restore your game.': '一旦错误被修复，你可以导入这个来恢复你的游戏。',
    'Keyboard Shortcuts': '键盘快捷键',
    'Hide upgrade': '隐藏已升级',
    'hatch': '孵化',
    'Hatch drones': '孵化工蜂',
    'Hatch max drones': '孵化工蜂到上限',
    'hatchery': '孵化场',
    'hatching': '孵化',
    'Here\'s the data we tried to save. You can import this through the': '这是我们试图保存的数据。可以导入这个通过',
    'Buy hatchery': '购买孵化场',
    'Buy all available upgrades': '购买全部可用升级',
    'Buy cheapest available upgrades': '购买最便宜的可用升级',
    'Buy expansion': '购买扩张',
    'Can\'t buy': '不能购买',
    'You earn': '你获得',
    'will cost': '会花费',
    'In total, they produce': '他们总共生产',
    'Each produces': '每个生产',
    'Exciting changes are coming to Swarm Simulator soon!': '令人兴奋的变化即将到来的模拟虫群!',
    'Drones are the lowest class of worker in your swarm. They continuously gather meat to feed your swarm.': '工蜂是你的虫群里面最低级的工人。它们不断地收集肉来喂养你的虫群。',
    '. Swarm Simulator needs this storage to save your game. It\'s not doing anything evil, I promise.': '。模拟虫群需要这个存储来保存你的游戏。我保证，它没有做任何坏事。',
    'If you think this is a bug, you can': '如果你觉得这是一个错误，你可以',
    'Insects are too icky, so we\'re changing our name. Also, we\'ll require graphics to play.': '虫子太恶心了，所以我们正在换名字。同时，我们需要图形来继续。',
    'Insects were too icky, so we\'re changing our name. Also, we now require graphics to play. Thanks to': '虫子太恶心了，所以我们正在换名字。同时，我们需要图形来继续。感谢',
    'and': '和',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "Oh no! ": "噢 不! ",
    "Open the ": "打开 ",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^(\d+) years (\d+) months$/, '$1 年 $2 个月'],
    [/^(\d+) hour$/, '$1 小时'],
    [/^(\d+) minute$/, '$1 分钟'],
    [/^(\d+) minutes$/, '$1 分钟'],
    [/^(.+)\/sec$/, '$1\/秒'],
    [/^(.+) larva$/, '$1 幼虫'],
    [/^(.+) larvae$/, '$1 幼虫'],
    [/^(.+) meta$/, '$1 肉'],
    [/^(.+) meat $/, '$1 肉 '],
    [/^(.+) meat$/, '$1 肉'],
    [/^(.+) drones $/, '$1 工蜂'],
    [/^At 100%, you'll stop earning (.+).$/, '在100%时，您将停止获得 $1。'],
    [/^Notify at (.+)× cost$/, '成本为 $1x 时通知'],
    [/^You own (.+) larvae.$/, '你拥有 $1 幼虫。'],
    [/^You own (.+) meat.$/, '你拥有 $1 肉。'],
    [/^You own (.+) drones.$/, '你拥有 $1 工蜂。'],
    [/^Buy cheapest (.+) upgrade$/, '购买最便宜的 $1 次升级'],
    [/^Buy all (.+) upgrade$/, '全部购买 $1 次升级'],
    [/^(.+)x: Normal$/, '$1x: 正常'],
    [/^(.+)x: Pause$/, '$1x: 暂停'],
    [/^Game speed: (.+)x$/, '游戏速度: $1x'],
    [/^Welcome back! While you were away for (.+), your swarm produced$/, '欢迎回来!在你离开的 $1，你的虫群产生了'],
    [/^You started playing (.+)$/, '你开始玩 $1'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);